name: Code Analysis - Scheduled

on:
  schedule:
    - cron: '59 23 * * *'

jobs:
  Analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  Notify:
    runs-on: ubuntu-latest
    needs: [Analyze]

    steps:
        - name: Heartbeat
          run: curl ${{ secrets.QL_HEARTBEAT_URL }}