name: Initialization

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm test
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        MONGO_SRV: ${{ secrets.MONGO_SRV }}
        VERSION: Pre-Deploy CI Build
        BOT_ID: ${{ secrets.BOT_ID }}
        ACTIVITY_TYPE: PLAYING
        ACTIVITY: with CI builds
        TESTING_SERVER_ID: ${{ secrets.TESTING_SERVER_ID }}
