name: PR Checks

on:
  pull_request:
    branches: [ main ]
    
jobs:
  Build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v3
    - name: Setup Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Reinstall packages
      run: npm ci
    - name: Initialize bot
      run: npm run test
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        MONGO_SRV: ${{ secrets.MONGO_SRV }}
        VERSION: Pull Request Checks
        BOT_ID: ${{ secrets.BOT_ID }}
        ACTIVITY_TYPE: PLAYING
        ACTIVITY: with PR builds
        TESTING_SERVER_ID: ${{ secrets.TESTING_SERVER_ID }}

  Eslint:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Run eslint checks
        run: npm run lint
      
  Analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2